scripts: support test configurations with NIC modifiers
A test host may have multiple NICs, hence the
need for some way to tell one from another.

Signed-off-by: Ivan Malov <ivan.malov@oktetlabs.ru>

diff --git a/scripts/check_cfg b/scripts/check_cfg
--- a/scripts/check_cfg
+++ b/scripts/check_cfg
@@ -154,6 +154,8 @@ check_cfg () {
     local user="$2"
     local steal="$3"
     local items
+    local item_user
+    local err
 
     if ! which item >/dev/null 2>&1 ; then
         if test "$(dnsdomainname)" = "oktetlabs.ru"; then
@@ -163,6 +165,37 @@ check_cfg () {
             return 1
         fi
         return 0
+    fi
+
+    # Checkif such item exists, otherwise try to cut various modifiers
+    if ! get_item_user "${cfg}" item_user err ; then
+        local cfg_wo_port="${cfg%-p?}"
+        local port_modifier="${cfg#${cfg_wo_port}}"
+
+        if test -n "${port_modifier}" \
+                && get_item_user "${cfg_wo_port}" item_user err ; then
+            cfg="${cfg_wo_port}"
+        else
+            local cfg_wo_nic="${cfg_wo_port}"
+
+            cfg_wo_nic="${cfg_wo_nic%-mlx}"
+            cfg_wo_nic="${cfg_wo_nic%-sfc}"
+            cfg_wo_nic="${cfg_wo_nic%-x710}"
+            if test "${cfg_wo_nic}" != "${cfg_wo_port}" ; then
+                if get_item_user "${cfg_wo_nic}${port_modifier}" \
+                        item_user err ; then
+                    cfg="${cfg_wo_nic}${port_modifier}"
+                elif  get_item_user "${cfg_wo_nic}" item_user err ; then
+                    cfg="${cfg_wo_nic}"
+                else
+                    echo "Item for '${cfg_wo_nic}' not found" >&2
+                    exit 1
+                fi
+            else
+                echo "Item for '${cfg_wo_port}' not found" >&2
+                exit 1
+            fi
+        fi
     fi
 
     test -n "${user}" || user="$(id -nu)"
